/**
 * Created. 2022-07-09
 */
export enum GithubLanguageKind {
  C = 'C',
  Clojure = 'Clojure',
  CoffeeScript = 'CoffeeScript',
  CPlusPlus = 'C++',
  CSharp = 'C#',
  CSS = 'CSS',
  Dart = 'Dart',
  Elixir = 'Elixir',
  Elm = 'Elm',
  Erlang = 'Erlang',
  FSharp = 'F#',
  Go = 'Go',
  Groovy = 'Groovy',
  Haskell = 'Haskell',
  HTML = 'HTML',
  Java = 'Java',
  JavaScript = 'JavaScript',
  Julia = 'Julia',
  Kotlin = 'Kotlin',
  Lua = 'Lua',
  Markdown = 'Markdown',
  MATLAB = 'MATLAB',
  Nix = 'Nix',
  ObjectiveC = 'Objective-C',
  OCaml = 'OCaml',
  Perl = 'Perl',
  PHP = 'PHP',
  Python = 'Python',
  R = 'R',
  Ruby = 'Ruby',
  Rust = 'Rust',
  Scala = 'Scala',
  SCSS = 'SCSS',
  Shell = 'Shell',
  Stylus = 'Stylus',
  Swift = 'Swift',
  TypeScript = 'TypeScript',
  VimScript = 'Vim Script',
}
