import { Box, Heading } from '@chakra-ui/react';
import type { GetServerSidePropsContext, NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import Layout from '../foundation/components/Layout';
import FancyUserCard from '../search/components/FancyUserCard';
import GithubUsersSearchBar from '../search/components/GithubUsersSearchBar';
import { useGithubUsersSearchHistory } from '../search/hooks/useGithubUsersSearchHistory';
import { pluralize } from '../utils/pluralize.util';
import { SearchUser } from './api/models/user.model';

interface Props {
  searchUsers: SearchUser[];
}

const Search: NextPage<Props> = ({ searchUsers }) => {
  const { initGithubUsersSearchHistory } = useGithubUsersSearchHistory();
  const router = useRouter();
  const { q } = router.query;

  useEffect(() => {
    // TODO: Run initGithubUsersSearchHistory only once when starting app.
    initGithubUsersSearchHistory();
  }, []);

  return (
    <>
      <Head>
        <title>Giteye | Search: {q}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <GithubUsersSearchBar initalSearchValue={q as string} />

        <Heading style={{ margin: '16px auto', textAlign: 'right' }} as="h4" size="sm" maxW="xl">
          {searchUsers.length} {pluralize('result', searchUsers.length)}
        </Heading>

        <Box style={{ margin: '0 auto' }} maxW="xl">
          {searchUsers.map((searchUser) => (
            <FancyUserCard key={searchUser.id} searchUser={searchUser} />
          ))}
        </Box>
      </Layout>
    </>
  );
};

export async function getServerSideProps({ query }: GetServerSidePropsContext) {
  const { q } = query;

  const searchUsers: SearchUser[] = await fetch(`${process.env.API_ENDPOINT}/search/users/${q}`)
    .then((res) => res.json())
    .then((data: SearchUser[]) => data);

  return { props: { searchUsers } };
}

export default Search;
function initGithubUsersSearchHistory() {
  throw new Error('Function not implemented.');
}
