import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { SearchUser } from "../models/user.model";
import styles from "../styles/Home.module.css";

const Search: NextPage = ({ searchUsers }: any) => {
  const router = useRouter();
  const { q } = router.query;

  return (
    <div className={styles.container}>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Search: {q}</h1>
      <div>
        {searchUsers.map(({ id, login, avatar_url }) => (
          <div key={id}>
            <Image src={avatar_url} alt={login} width={80} height={80} />
            <div>{login}</div>
          </div>
        ))}
      </div>
    </div>
  );
};

export async function getServerSideProps({ query }: any) {
  const q = query.q;

  const searchUsers: SearchUser[] = await fetch(
    `http://localhost:8080/search/users/${q}`
  )
    .then((res) => res.json())
    .then((data: SearchUser[]) => data);

  return { props: { searchUsers } };
}

export default Search;
