import { Heading } from '@chakra-ui/react';
import type { GetServerSidePropsContext, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import Layout from '../foundation/components/Layout';
import GithubUsersSearchBar from '../search/components/GithubUsersSearchBar';
import { SearchUser } from './api/models/user.model';

interface Props {
  searchUsers: SearchUser[];
}

const Search: NextPage<Props> = ({ searchUsers }) => {
  const router = useRouter();
  const { q } = router.query;

  return (
    <>
      <Head>
        <title>Giteye | Search: {q}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <GithubUsersSearchBar initalSearchValue={q as string} />

        <Heading as="h4" size="sm">
          {searchUsers.length} results
        </Heading>

        <div>
          {searchUsers.map(({ id, login, avatar_url }) => (
            <div key={id}>
              <Image src={avatar_url} alt={login} width={80} height={80} />
              <div>id: {id}</div>
              <div>login: {login}</div>
            </div>
          ))}
        </div>
      </Layout>
    </>
  );
};

export async function getServerSideProps({ query }: GetServerSidePropsContext) {
  const { q } = query;

  const searchUsers: SearchUser[] = await fetch(`http://localhost:8080/search/users/${q}`)
    .then((res) => res.json())
    .then((data: SearchUser[]) => data);

  return { props: { searchUsers } };
}

export default Search;
